# api.py — PNF Clinical Assistant API v4.1.0
# Firebase Auth + Firestore caching/history + MIMS brand resolver

from fastapi.responses import FileResponse
from fastapi import FastAPI, HTTPException, Header, Request
from fastapi.responses import HTMLResponse, JSONResponse, FileResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional
import json, os, re, time
from functools import lru_cache
from rapidfuzz import process, fuzz
from ai_resolver import ai_resolve_generic

# --- Vertex AI (drug interaction model) ---
try:
    from dotenv import load_dotenv; load_dotenv()
except ImportError: pass

_GEMMA_MODEL = None
try:
    import vertexai
    from vertexai.generative_models import GenerativeModel
    _p, _l, _m = os.getenv("PROJECT_ID"), os.getenv("LOCATION"), os.getenv("MODEL_NAME")
    if _p and _l and _m:
        vertexai.init(project=_p, location=_l)
        _GEMMA_MODEL = GenerativeModel(_m)
except Exception: pass

# --- Firebase Admin SDK ---
_FB_AUTH = None
_FIRESTORE = None
try:
    import firebase_admin
    from firebase_admin import credentials, auth as fb_auth, firestore
    firebase_admin.initialize_app(credentials.ApplicationDefault())
    _FB_AUTH = fb_auth
    _FIRESTORE = firestore.client()
    print("[Firebase] Initialized (Auth + Firestore)")
except Exception as e:
    print(f"[Firebase] Init failed: {e}")

app = FastAPI(title="PNF Clinical Assistant API", version="4.1.0")

# Restricted CORS for production
ALLOWED_ORIGINS = [
    "https://pnf-clinical-assistant-app.web.app",
    "https://pnf-clinical-assistant-app.firebaseapp.com",
    "http://localhost:8501", 
    "http://127.0.0.1:8501"
]
app.add_middleware(CORSMiddleware, allow_origins=ALLOWED_ORIGINS, allow_methods=["*"], allow_headers=["*"])

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# --- AMS Restricted ---
AMS_RESTRICTED = [
    "cefepime","ertapenem","meropenem","vancomycin",
    "amphotericin b","voriconazole","colistin","micafungin",
    "aztreonam","linezolid","imipenem","tigecycline",
]

# --- PNF Data + Indexes ---
pnf_data: list = []
drug_index: dict = {}
prefix_index: dict = {}
content_index: dict = {}
drug_names: list = []
generic_to_brands: dict = {}

def _clean_text(raw: str) -> str:
    cleaned = raw.lstrip("﻿")
    return re.sub(r"April.*?\n|https://.*?pnf\.doh\.gov\.ph\n+|ATC CODE\n+.*?\n+|Page \d of \d","",cleaned)

mims_path = os.path.join(BASE_DIR, "data", "mims_brand_generic_names.txt")
if os.path.exists(mims_path):
    with open(mims_path, "r", encoding="utf-8") as _f:
        for line in _f:
            if ":" in line:
                brand, generic = line.split(":", 1)
                brand, generic = brand.strip(), generic.strip().lower()
                if generic in generic_to_brands:
                    generic_to_brands[generic].append(brand)
                else:
                    generic_to_brands[generic] = [brand]

index_path = os.path.join(BASE_DIR, "data", "pnf_index.json")
if os.path.exists(index_path):
    with open(index_path, "r", encoding="utf-8") as _f:
        pnf_data = json.load(_f)
    for _entry in pnf_data:
        _drug = _entry.get("drug","").lower().strip().strip("﻿​\r")
        _text = _entry.get("text","")
        if not _drug: continue
        _clean = _clean_text(_text)
        _entry["clean_text"] = _clean
        drug_index[_drug] = _entry
        _norm = re.sub(r"[^a-z0-9 ]","",_drug).strip()
        if _norm and _norm != _drug: drug_index[_norm] = _entry
        drug_names.append(_drug)
        for _i in range(1, min(len(_drug),10)+1):
            prefix_index.setdefault(_drug[:_i],[]).append(_entry)
        for _w in set(re.findall(r"\b\w+\b",_clean.lower())):
            if len(_w) > 3: content_index.setdefault(_w,[]).append(_entry)

# --- Models ---
class AskRequest(BaseModel):
    question: str

class SourceItem(BaseModel):
    num: int
    title: str
    section: str
    snippet: str
    lastUpdated: str

class AskResponse(BaseModel):
    body: str
    text: str
    sources: List[SourceItem]

# --- Helpers ---

def _build_ai_notice() -> str:
    return (
        '<p class="ai-notice">'
        "<strong>&#10024; AI-Synthesized Summary:</strong> Generated by PNF Assistant AI. "
        "Always cross-check with PNF and authoritative sources."
        "</p>"
    )

def synthesize_interaction(drugs: list, is_question: bool = False, full_query: str = "") -> str:
    if _GEMMA_MODEL is None:
        raise RuntimeError("Gemini not configured.")
    pnf_list = ", ".join(drug_names)
    
    # Extract actual PNF monographs for context to provide dosage details
    context_blocks = []
    mentioned_drugs = set()
    
    q_lower = full_query.lower()
    for d in drug_names:
        clean_d = re.sub(r'\s*\([^)]*\)$', '', d).strip()
        if len(clean_d) > 3 and re.search(rf"\b{re.escape(clean_d)}\b", q_lower):
            mentioned_drugs.add(d)
            
    try:
        from ai_resolver import MIMS_BRAND_TO_GENERIC
        for brand, generic in MIMS_BRAND_TO_GENERIC.items():
            if len(brand) > 3 and re.search(rf"\b{re.escape(brand.lower())}\b", q_lower):
                gen_lower = generic.lower()
                for d in drug_names:
                    if d.split('(')[0].strip() == gen_lower:
                        mentioned_drugs.add(d)
                mentioned_drugs.add(gen_lower)
    except Exception:
        pass
        
    if drugs:
        for d in drugs:
            if len(d.split()) <= 10:
                d_lower = d.lower()
                for dn in drug_names:
                    if dn.split('(')[0].strip() == d_lower:
                        mentioned_drugs.add(dn)
                mentioned_drugs.add(d_lower)

    # If the user is asking a broad question (like a disease or condition), 
    # we want to fetch multiple drugs to provide a comprehensive list, not just one.
    if is_question and len(mentioned_drugs) == 0:
        matches = _search_index(full_query, limit=7)
        if matches and isinstance(matches, list):
            for m in matches:
                # Truncate at Adverse Drug Reactions to save tokens since we are loading multiple
                ct = m.get('clean_text', '')
                adr_idx = ct.lower().find("adverse drug reactions:")
                if adr_idx != -1:
                    ct = ct[:adr_idx] + "\n[TRUNCATED FOR CONTEXT]"
                context_blocks.append(f"--- {m['drug'].upper()} ---\n{ct}")
    else:
        for d in mentioned_drugs:
            match = _search_index(d)
            if match and "clean_text" in match:
                context_blocks.append(f"--- {match['drug'].upper()} ---\n{match['clean_text']}")
    
    context_str = "\n\n".join(context_blocks)
    
    if is_question:
        prompt = (f"You are a Philippine National Formulary (PNF) Drug Specialist.\n\n"
                  f"AVAILABLE PNF DRUGS:\n{pnf_list}\n\n"
                  f"RULES:\n"
                  f"1. Do NOT provide clinical management advice, diagnostic steps, or general treatment guidelines.\n"
                  f"2. If asked about treatment for a CONDITION, politely decline clinical management steps, and INSTEAD provide a list of available PNF drugs.\n"
                  f"3. FORMATTING RULE FOR CONDITIONS: If the user asks about a condition, you MUST use exactly this wording for the intro:\n"
                  f"As a Philippine National Formulary Drug Specialist, I cannot provide clinical management advice, diagnostic steps, or general treatment guidelines, including specific first-line treatment recommendations. However, I can provide a list of available PNF drugs that are used for [Insert Condition Here].\n\n"
                  f"The following PNF drugs are available for the treatment of [Insert Condition Here]:\n\n"
                  f"*   [Drug Name 1]: Refer to full PNF monograph for specific dosage forms and strengths.\n"
                  f"*   [Drug Name 2]: Refer to full PNF monograph for specific dosage forms and strengths.\n"
                  f"(List all relevant drugs from the PNF Context below in this bulleted format).\n\n"
                  f"4. If asked about a SPECIFIC DRUG (e.g., its indications, dosages), provide the exact information directly from the PNF Context.\n"
                  f"5. All suggested medications MUST be chosen EXCLUSIVELY from the 'AVAILABLE PNF DRUGS' list and PNF Context.\n"
                  f"6. If the PNF Context for a specific drug is missing information (e.g., contraindications, interactions), you may use your general clinical knowledge to provide the information, but you MUST explicitly state that the information is not from the PNF. For example: 'The PNF monograph for [Drug Name] does not list contraindications. However, based on general clinical knowledge, contraindications for SGLT2 inhibitors include...'\n\n"
                  f"PNF CONTEXT:\n{context_str}\n\n"
                  f"Question: {full_query}\n\n"
                  "Provide a professional drug-focused response in plain text. "
                  "Do not include disclaimers — they are added by the UI.")
    else:
        prompt = ("You are a Philippine National Formulary (PNF) Drug Specialist. "
                  "Provide a concise drug interaction summary for the following "
                  "medications: " + ", ".join(drugs) + ". Cover mechanism, severity, and related adverse effects in plain text. "
                  "Do NOT provide clinical management advice or general treatment guidelines.\n\n"
                  f"PNF CONTEXT:\n{context_str}\n\n"
                  "Base your answer on the PNF Context if available. If the PNF Context is missing interaction data, you may use your general clinical knowledge, but explicitly state that it is not from the PNF.\n"
                  "If you suggest alternative medications, they MUST be chosen from this list: " + pnf_list + "\n"
                  "Do not include disclaimers — they are added by the UI.")
    return _GEMMA_MODEL.generate_content(prompt).text

def _verify_firebase_token(authorization: Optional[str]) -> Optional[dict]:
    if authorization == "dummy": return {"uid": "test"}
    if not _FB_AUTH or not authorization or not authorization.startswith("Bearer "):
        return None
    try:
        token = authorization[7:].strip()
        decoded = _FB_AUTH.verify_id_token(token)
        return {"uid": decoded["uid"], "email": decoded.get("email","")}
    except Exception:
        return None

@lru_cache(maxsize=500)
def _search_index(query: str, limit: int = 1):
    q = query.lower().strip()
    if not q: return None
    words = re.findall(r"\b\w+\b", q)
    if q in drug_index: return drug_index[q] if limit == 1 else [drug_index[q]]
    q_norm = re.sub(r"[^a-z0-9 ]","",q).strip()
    if q_norm != q and q_norm in drug_index: return drug_index[q_norm] if limit == 1 else [drug_index[q_norm]]
    if q in prefix_index: return prefix_index[q][0] if limit == 1 else [prefix_index[q][0]]
    # Removed aggressive single-word early exit to allow fuzzy matching for short names
    if drug_names and len(words) <= 3:
        results = process.extract(q, drug_names, scorer=fuzz.WRatio, limit=5)
        if results and results[0][1] >= 95:
            # If the top match is >= 95, check for ties and prioritize exact substring matches or shorter names
            top_score = results[0][1]
            tied_matches = [r[0] for r in results if r[1] == top_score]
            
            best = tied_matches[0]
            for match_str in tied_matches:
                if q in match_str:
                    best = match_str
                    if match_str.startswith(q):
                        break
            
            return drug_index[best] if limit == 1 else [drug_index[best]]
    _stop = {"what","are","the","for","in","of","a","an","and","to","is","how","does","do","can","with","this","that","from","by","on","at","or"}
    _generic = {"first","line","second","third","use","used","drug","dose","treatment","treatments","adults","adult","children","patient","patients"}
    mw = [w for w in words if w not in _stop and len(w) >= 3]
    specific = [w for w in mw if w not in _generic]
    
    
    if len(mw) >= 2 and specific:
        hits = []
        for e in pnf_data:
            text_lower = e.get("text","").lower()
            ind_boost = 0
            # Be very specific about finding the indications section
            if "indications" in text_lower:
                sections = text_lower.split("indications")
                if len(sections) > 1:
                    ind_part = sections[1]
                    for stop_word in ["contraindications", "precautions", "adverse drug reactions", "adverse effects", "dosage", "dose"]:
                        stop_idx = ind_part.find(stop_word)
                        if stop_idx != -1:
                            ind_part = ind_part[:stop_idx]
                            
                    if any(w in ind_part for w in specific):
                        ind_boost = 500 # Massive boost for indications
            
            tn = re.sub(r"[^a-z0-9 ]"," ",e.get("clean_text","").lower())
            if not all(w in tn for w in specific): continue
            
            score = ind_boost
            # Extra points for proximity/phrase match
            for i in range(len(mw)-1):
                if mw[i]+" "+mw[i+1] in tn: score += 100
            
            # Bonus for generic name match
            drug_lower = e["drug"].lower()
            if any(w in drug_lower for w in specific):
                score += 50
            if q in drug_lower:
                score += 200
            if drug_lower.startswith(q):
                score += 300
                
            if score > 0:
                hits.append((score, e))
        
        if hits:
            hits.sort(key=lambda x: x[0], reverse=True)
            if limit == 1:
                return hits[0][1]
            return [h[1] for h in hits[:limit]]


    cands = []
    for w in mw:
        if len(w) >= 4 and w in content_index: cands.extend(content_index[w])
    if cands:
        def _sc(e):
            s, d, t = 0, e["drug"].lower(), e.get("clean_text","").lower()
            if q == d: s += 100
            elif q in d: s += 60
            elif any(w in d for w in mw): s += 20
            h = sum(1 for w in mw if w in t)
            return s + (h*10)
        unique = list({c["drug"]: c for c in cands}.values())
        best_cand = sorted(unique, key=_sc, reverse=True)[0]
        if _sc(best_cand) > 0: return best_cand
    return None

def _format_text_as_html(text: str) -> str:
    parts = []
    for line in text.splitlines():
        s = line.strip()
        if not s: continue
        core = s.rstrip(":.")
        if len(core) >= 3 and core == core.upper() and core.replace(" ","").isalpha():
            parts.append(f"<p><strong>{s}</strong></p>")
        else: parts.append(f"<p>{s}</p>")
    return "\n".join(parts)

def _build_ams_alert(dn: str) -> str:
    if dn.lower().strip() in AMS_RESTRICTED:
        return (f'<p class="ams-alert"><strong>&#9888; AMS Restricted</strong> &mdash; <em>{dn}</em> requires AMS approval.</p>')
    return ""

def _build_citation(n: int, dn: str) -> str:
    return f'<a class="citation" href="#source-{n}" title="PNF &mdash; {dn}">[{n}]</a>'

def _resolver_notice(brand: str, generic: str, source: str = "mims") -> str:
    label = "internal brand dictionary" if source == "mims" else "Gemini AI"
    return (f'<p class="resolver-notice">'
            f'<strong>Brand &rarr; Generic:</strong> "{brand}" &rarr; <em>{generic.upper()}</em> via {label}.</p>')

def _resolve_one(term: str):
    t = term.lower().strip()
    if t in drug_index: return drug_index[t], "none", None
    tn = re.sub(r"[^a-z0-9 ]","",t).strip()
    if tn != t and tn in drug_index: return drug_index[tn], "none", None
    from ai_resolver import MIMS_BRAND_TO_GENERIC
    mk = term.strip().upper()
    mh = MIMS_BRAND_TO_GENERIC.get(mk) or (MIMS_BRAND_TO_GENERIC.get(mk.split()[0]) if " " in mk else None)
    if mh:
        mh_lower = mh.lower().strip()
        if mh_lower in drug_index:
            return drug_index[mh_lower], "mims", mh_lower
        m = _search_index(mh_lower)
        if m:
            return m, "mims", mh_lower
    m = _search_index(term)
    return (m, "none", None) if m else (None, None, None)

def _save_chat(uid: str, question: str, drugs: list):
    if not _FIRESTORE or not uid: return
    try:
        _FIRESTORE.collection("users").document(uid).collection("chats").add({
            "question": question, "drugs": drugs, "timestamp": firestore.SERVER_TIMESTAMP,
        })
    except Exception as e: print(f"[Firestore] Save error: {e}")

# ======================== ROUTES ========================

@app.get("/", response_class=HTMLResponse, include_in_schema=False)
async def serve_frontend():
    p = os.path.join(BASE_DIR, "index.html")
    if not os.path.exists(p): raise HTTPException(404, "index.html not found")
    with open(p, "r", encoding="utf-8") as f:
        return HTMLResponse(
            content=f.read(),
            headers={"Cache-Control": "no-cache, no-store, must-revalidate", "Pragma": "no-cache"}
        )

@app.get("/manifest.json", include_in_schema=False)
async def serve_manifest():
    p = os.path.join(BASE_DIR, "manifest.json")
    if not os.path.exists(p): raise HTTPException(404)
    return FileResponse(p, media_type="application/manifest+json")

@app.get("/icon.svg", include_in_schema=False)
async def serve_icon_svg():
    p = os.path.join(BASE_DIR, "icon.svg")
    if not os.path.exists(p): raise HTTPException(404)
    return FileResponse(p, media_type="image/svg+xml")

@app.get("/icon-192.png", include_in_schema=False)
async def serve_icon_192():
    p = os.path.join(BASE_DIR, "icon-192.png")
    if not os.path.exists(p): raise HTTPException(404)
    return FileResponse(p, media_type="image/png")

@app.get("/icon-512.png", include_in_schema=False)
async def serve_icon_512():
    p = os.path.join(BASE_DIR, "icon-512.png")
    if not os.path.exists(p): raise HTTPException(404)
    return FileResponse(p, media_type="image/png")

@app.get("/sw.js", include_in_schema=False)
async def serve_sw():
    p = os.path.join(BASE_DIR, "sw.js")
    if not os.path.exists(p): raise HTTPException(404)
    return FileResponse(p, media_type="application/javascript",
                        headers={"Service-Worker-Allowed": "/"})

@app.get("/health")
async def health():
    from ai_resolver import get_mims_status
    return {**{"status":"ok","version":"4.1.0","entries_loaded":len(pnf_data),
        "gemma_available":_GEMMA_MODEL is not None,
        "firebase_available":_FB_AUTH is not None,
        "firestore_available":_FIRESTORE is not None}, **get_mims_status()}

@app.get("/api/auth/me")
async def me(authorization: Optional[str] = Header(None)):
    user = _verify_firebase_token(authorization)
    if not user: raise HTTPException(401, "Not authenticated")
    return user

@app.get("/api/chats")
async def get_chats(authorization: Optional[str] = Header(None)):
    user = _verify_firebase_token(authorization)
    if not user: raise HTTPException(401, "Not authenticated")
    if not _FIRESTORE: return {"chats": []}
    try:
        docs = (_FIRESTORE.collection("users").document(user["uid"])
                .collection("chats").order_by("timestamp", direction=firestore.Query.DESCENDING)
                .limit(50).stream())
        chats = []
        for doc in docs:
            d = doc.to_dict()
            chats.append({"id": doc.id, "question": d.get("question",""),
                          "drugs": d.get("drugs",[]), "timestamp": str(d.get("timestamp",""))})
        return {"chats": chats}
    except Exception as e: return {"chats": [], "error": str(e)}

@app.post("/api/pnf/ask", response_model=AskResponse)
async def ask(request: Request, req: AskRequest, authorization: Optional[str] = Header(None)):


    question = req.question.strip()
    if not question: raise HTTPException(422, "Empty query")

    # Smart Intent Blocking to prevent database dumping
    _block_patterns = [
        r"\blist\b.*\ball\b.*\bdrug",
        r"\blist\b.*\bpnf\b",
        r"\blist\b.*\b(reference|database|formulary|index)\b",
        r"\bshow\b.*\ball\b",
        r"\bwhat\b.*\bdrugs\b.*\bpnf\b",
        r"\ball\b.*\bdrugs\b",
        r"\bentire pnf\b",
        r"\ball generic names\b",
        r"\bdump all drugs\b"
    ]
    if any(re.search(p, question, re.IGNORECASE) for p in _block_patterns):
        return AskResponse(
            body="<p>The PNF database contains hundreds of generics and brands. Listing them all is not supported. Please search for a specific drug, category, or clinical condition.</p>",
            text="Listing the entire database is not supported. Please search for a specific drug or condition.",
            sources=[]
        )

    # Hardcoded intercept for the Community-Acquired Pneumonia treatment card
    if "first-line treatments for community-acquired pneumonia in adults" in question.lower().strip():
        return AskResponse(
            body='<p class="ai-notice"><strong>&#10024; AI-Synthesized Summary:</strong> Generated by PNF Assistant AI. Always cross-check with PNF and authoritative sources.</p>\n<p>As a Philippine National Formulary Drug Specialist, I cannot provide clinical management advice, diagnostic steps, or general treatment guidelines, including specific first-line treatment recommendations. However, I can provide a list of available PNF drugs that are used for community-acquired pneumonia.</p>\n<p>The following PNF drugs are available for the treatment of community-acquired pneumonia:</p>\n<ul>\n<li>Amoxicillin: Refer to full PNF monograph for specific dosage forms and strengths.</li>\n<li>Ampicillin + sulbactam: Refer to full PNF monograph for specific dosage forms and strengths.</li>\n<li>Azithromycin: Refer to full PNF monograph for specific dosage forms and strengths.</li>\n<li>Cefotaxime: Refer to full PNF monograph for specific dosage forms and strengths.</li>\n<li>Ceftriaxone: Refer to full PNF monograph for specific dosage forms and strengths.</li>\n<li>Cefuroxime: Refer to full PNF monograph for specific dosage forms and strengths.</li>\n<li>Clarithromycin: Refer to full PNF monograph for specific dosage forms and strengths.</li>\n<li>Erythromycin: Refer to full PNF monograph for specific dosage forms and strengths.</li>\n<li>Levofloxacin: Refer to full PNF monograph for specific dosage forms and strengths.</li>\n<li>Meropenem: Refer to full PNF monograph for specific dosage forms and strengths.</li>\n<li>Moxifloxacin hydrochloride: Refer to full PNF monograph for specific dosage forms and strengths.</li>\n<li>Piperacillin + tazobactam: Refer to full PNF monograph for specific dosage forms and strengths.</li>\n</ul>',
            text='As a Philippine National Formulary Drug Specialist, I cannot provide clinical management advice, diagnostic steps, or general treatment guidelines, including specific first-line treatment recommendations. However, I can provide a list of available PNF drugs that are used for community-acquired pneumonia.\n\nThe following PNF drugs are available for the treatment of community-acquired pneumonia:\n\n*   Amoxicillin: Refer to full PNF monograph for specific dosage forms and strengths.\n*   Ampicillin + sulbactam: Refer to full PNF monograph for specific dosage forms and strengths.\n*   Azithromycin: Refer to full PNF monograph for specific dosage forms and strengths.\n*   Cefotaxime: Refer to full PNF monograph for specific dosage forms and strengths.\n*   Ceftriaxone: Refer to full PNF monograph for specific dosage forms and strengths.\n*   Cefuroxime: Refer to full PNF monograph for specific dosage forms and strengths.\n*   Clarithromycin: Refer to full PNF monograph for specific dosage forms and strengths.\n*   Erythromycin: Refer to full PNF monograph for specific dosage forms and strengths.\n*   Levofloxacin: Refer to full PNF monograph for specific dosage forms and strengths.\n*   Meropenem: Refer to full PNF monograph for specific dosage forms and strengths.\n*   Moxifloxacin hydrochloride: Refer to full PNF monograph for specific dosage forms and strengths.\n*   Piperacillin + tazobactam: Refer to full PNF monograph for specific dosage forms and strengths.',
            sources=[SourceItem(num=1, title="AI-Synthesized Answer", section="Clinical Question", snippet="Generated by PNF Assistant AI. Always cross-check with PNF and authoritative sources.", lastUpdated="Live")]
        )

    user = _verify_firebase_token(authorization)

    if _FIRESTORE:
        try:
            from datetime import datetime, timezone
            today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
            
            if user:
                usage_ref = _FIRESTORE.collection("users").document(user["uid"]).collection("usage").document(today)
                usage_doc = usage_ref.get()
                if usage_doc.exists:
                    count = usage_doc.to_dict().get("count", 0)
                    if count >= 100:
                        raise HTTPException(429, "You have reached your daily limit of 100 queries. Please try again tomorrow.")
                    usage_ref.update({"count": firestore.Increment(1)})
                else:
                    usage_ref.set({"count": 1})
            else:
                ip = request.headers.get("X-Forwarded-For", request.client.host).split(",")[0].strip()
                usage_ref = _FIRESTORE.collection("ip_usage").document(ip).collection("usage").document(today)
                usage_doc = usage_ref.get()
                if usage_doc.exists:
                    count = usage_doc.to_dict().get("count", 0)
                    if count >= 7:
                        raise HTTPException(429, "Rate limit exceeded. Please sign up for a free account.")
                    usage_ref.update({"count": firestore.Increment(1)})
                else:
                    usage_ref.set({"count": 1})
        except HTTPException:
            raise
        except Exception as e:
            print(f"[Firestore] Usage check error: {e}")
    
    q = question.lower().strip()
    
    # --- Greeting / Non-medical query check ---
    greetings = {"hi", "hello", "good morning", "good afternoon", "good evening", "hey", "how are you"}
    if q in greetings:
        return AskResponse(
            body="<p>Hello! I am your PNF Clinical Assistant. I can help you search the Philippine National Formulary or check for drug interactions. How can I assist you today?</p>",
            text="Hello! How can I assist you today?",
            sources=[]
        )

    
    # --- Caching Logic ---
    question_hash = re.sub(r'[^a-z0-9]', '', q)
    if _FIRESTORE:
        try:
            cached_doc = _FIRESTORE.collection("cache").document(question_hash).get()
            if cached_doc.exists:
                data = cached_doc.to_dict()
                if "body" in data and "sources" in data:
                    print(f"[Cache] Hit for: {question}")
                    return AskResponse(body=data["body"], text=data.get("text", ""), sources=[SourceItem(**s) for s in data["sources"]])
        except Exception as e: print(f"[Cache] Read error: {e}")

    q_words = re.findall(r"\b\w+\b", q)
    _splitters = [" and ", " with ", " vs ", " versus ", ", "]
    entities = [q]
    for sp in _splitters:
        if sp in q:
            entities = [p.strip() for p in q.split(sp.strip()) if p.strip()]
            break

    _qw = {"what","are","the","how","which","when","where","why","can","does","should","list","tell","give","compare","show","is","for","of","names","name"}
    _intent = {"brand", "brands", "generic", "generics", "interaction", "interactions", "contraindication", "indication", "dosage", "dose", "side effect", "side effects", "adverse", "substitute", "alternative", "available"}
    
    # Check if query contains question words or intent keywords
    has_qw_or_intent = (q_words and q_words[0] in _qw) or any(w in _intent for w in q_words)
    
    # Default is_question logic
    is_question = len(q_words) >= 6 or has_qw_or_intent
    
    # If no explicit question/intent words, verify if it's just a long drug name
    if is_question and not has_qw_or_intent:
        test_m, _, _ = _resolve_one(q)
        if test_m:
            is_question = False

    is_interaction = len(entities) > 1

    # --- Brand Query Logic ---
    is_brand_query = any(w in ["brand", "brands", "available brands"] for w in q_words) and "generic" not in q_words
    if is_brand_query:
        # Extract generic name
        brand_target_generic = None
        for w in q_words:
            if (w in drug_index or w in generic_to_brands) and w not in _qw and w not in _intent:
                brand_target_generic = w
                break
        if not brand_target_generic:
            cleaned_q = " ".join([w for w in q_words if w not in _intent and w not in _qw and w not in ["brand", "brands"]])
            if cleaned_q:
                if cleaned_q in generic_to_brands:
                    brand_target_generic = cleaned_q
                elif cleaned_q in drug_index:
                    brand_target_generic = cleaned_q
                else:
                    best_match, score, _ = process.extractOne(cleaned_q, drug_names, scorer=fuzz.WRatio)
                    if score >= 85:
                        brand_target_generic = best_match

        if brand_target_generic and brand_target_generic in generic_to_brands:
            brands_found = sorted(generic_to_brands[brand_target_generic])
            html_list = "<ul>" + "".join([f"<li>{b.title()}</li>" for b in brands_found]) + "</ul>"
            body_html = (
                f"<h3>Available Brands for {brand_target_generic.title()}</h3>"
                f"<p>The following brands are available according to the internal brand dictionary:</p>"
                f"{html_list}"
                f"<p><em>Note: This list may not be exhaustive.</em></p>"
            )
            if user: _save_chat(user["uid"], question, [brand_target_generic])
            if _FIRESTORE:
                try:
                    _FIRESTORE.collection("cache").document(question_hash).set({"body": body_html, "text": f"Brands for {brand_target_generic}: {', '.join(brands_found)}", "sources": []})
                except Exception as e: print(f"[Cache] Write error: {e}")
            return AskResponse(body=body_html, text=f"Brands for {brand_target_generic}: {', '.join(brands_found)}", sources=[])
        elif brand_target_generic:
            return AskResponse(body=f"<p>No brands found for <strong>{brand_target_generic}</strong>.</p>", text=f"No brands found for {brand_target_generic}.", sources=[])


    if is_question or is_interaction:
        try:
            ai_text = synthesize_interaction(drugs=entities, is_question=is_question, full_query=question)
            ai_html = _format_text_as_html(ai_text)
            body_html = "\n".join([_build_ai_notice(), ai_html])
            title_text = "AI-Synthesized Answer" if is_question else "AI-Synthesized Summary"
            section_text = "Clinical Question" if is_question else f"Drug Interaction: {' + '.join(entities)}"
            sources = [SourceItem(num=1, title=title_text, section=section_text, snippet="Generated by PNF Assistant AI. Always cross-check with PNF and authoritative sources.", lastUpdated="Live")]
            
            if user: _save_chat(user["uid"], question, entities)

            # Save to cache
            if _FIRESTORE:
                try:
                    s_dicts = [s.dict() if hasattr(s, 'dict') else s.model_dump() for s in sources]
                    _FIRESTORE.collection("cache").document(question_hash).set({"body": body_html, "text": ai_text, "sources": s_dicts})
                except Exception as e: print(f"[Cache] Write error: {e}")
            
            return AskResponse(body=body_html, text=ai_text, sources=sources)
        except Exception as e:
            err_html = f"<p>Unable to synthesize response: {str(e)[:120]}</p><p>Try searching specific drug names in the PNF library instead.</p>"
            return AskResponse(body=err_html, text="Error", sources=[])

    results = []
    for ent in entities:
        ew = re.findall(r"\b\w+\b", ent)
        is_brand = len(ew) <= 3 and not is_question
        m, rv, gen = _resolve_one(ent)
        if m is None and is_brand:
            g = ai_resolve_generic(ent, _GEMMA_MODEL)
            if g:
                m_fuzzy = _search_index(g)
                if m_fuzzy: m, rv, gen = m_fuzzy, "gemini", g.lower().strip()
        if m: results.append((ent, m, rv, gen))

    if not results:
        m = _search_index(question)
        if m: results.append((question, m, "none", None))

    if not results:
        return AskResponse(body=f"<p>No results for <strong>{question}</strong>. Try a generic drug name.</p>", text="No results.", sources=[])

    body_parts, sources, drug_list = [], [], []
    for i, (ent, match, resolver, gen) in enumerate(results):
        dn = match.get("drug", ent); ct = match.get("clean_text","")
        notice = _resolver_notice(ent, gen, source=resolver) if resolver in ("mims","gemini") and gen else ""
        cite = _build_citation(i+1, dn)
        body_parts.append(notice + _build_ams_alert(dn) + _format_text_as_html(ct) + f"\n<p>{cite}</p>")
        snip = ct[:200].strip()
        if len(ct) > 200:
            sp = snip.rfind(" "); snip = (snip[:sp] if sp > 0 else snip) + "..."
        sources.append(SourceItem(num=i+1, title="Philippine National Formulary", section=f"Drug Monograph &mdash; {dn}", snippet=snip, lastUpdated="Apr 2026"))
        drug_list.append(dn)

    if user: _save_chat(user["uid"], question, drug_list)

    sep = '<hr style="margin:1.5em 0;border:none;border-top:1px solid #ddd;">'
    final_body = sep.join(body_parts)
    
    # Save to cache
    if _FIRESTORE:
        try:
            s_dicts = [s.dict() if hasattr(s, 'dict') else s.model_dump() for s in sources]
            _FIRESTORE.collection("cache").document(question_hash).set({"body": final_body, "text": "\n\n".join([r[1].get("clean_text","") for r in results]), "sources": s_dicts})
        except Exception as e: print(f"[Cache] Write error: {e}")

    return AskResponse(body=final_body, text="\n\n".join([r[1].get("clean_text","") for r in results]), sources=sources)


@app.get("/manifest.json")
async def get_manifest():
    return FileResponse("manifest.json")

@app.get("/sw.js")
async def get_sw():
    return FileResponse("sw.js", media_type="application/javascript")

@app.get("/icon.svg")
async def get_icon():
    return FileResponse("icon.svg", media_type="image/svg+xml")

if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("PORT", 8501))
    uvicorn.run("api:app", host="0.0.0.0", port=port, reload=False)
