# api.py — PNF Clinical Assistant API v4.0.0
# Firebase Auth (client-side) + Firestore chat history + MIMS brand resolver

from fastapi import FastAPI, HTTPException, Header, Request
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional
import json, os, re, time
from functools import lru_cache
from rapidfuzz import process, fuzz
from ai_resolver import ai_resolve_generic

# --- Vertex AI (drug interaction model) ---
try:
    from dotenv import load_dotenv; load_dotenv()
except ImportError: pass

_GEMMA_MODEL = None
try:
    import vertexai
    from vertexai.generative_models import GenerativeModel
    _p, _l, _m = os.getenv("PROJECT_ID"), os.getenv("LOCATION"), os.getenv("MODEL_NAME")
    if _p and _l and _m:
        vertexai.init(project=_p, location=_l)
        _GEMMA_MODEL = GenerativeModel(_m)
except Exception: pass

# --- Firebase Admin SDK ---
_FB_AUTH = None
_FIRESTORE = None
try:
    import firebase_admin
    from firebase_admin import credentials, auth as fb_auth, firestore
    firebase_admin.initialize_app(credentials.ApplicationDefault())
    _FB_AUTH = fb_auth
    _FIRESTORE = firestore.client()
    print("[Firebase] Initialized (Auth + Firestore)")
except Exception as e:
    print(f"[Firebase] Init failed: {e}")

app = FastAPI(title="PNF Clinical Assistant API", version="4.0.0")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# --- AMS Restricted ---
AMS_RESTRICTED = [
    "cefepime","ertapenem","meropenem","vancomycin",
    "amphotericin b","voriconazole","colistin","micafungin",
    "aztreonam","linezolid","imipenem","tigecycline",
]

# --- PNF Data + Indexes ---
pnf_data: list = []
drug_index: dict = {}
prefix_index: dict = {}
content_index: dict = {}
drug_names: list = []

def _clean_text(raw: str) -> str:
    cleaned = raw.lstrip("﻿")
    return re.sub(r"April.*?\n|https://.*?pnf\.doh\.gov\.ph\n+|ATC CODE\n+.*?\n+|Page \d of \d","",cleaned)

index_path = os.path.join(BASE_DIR, "data", "pnf_index.json")
if os.path.exists(index_path):
    with open(index_path, "r", encoding="utf-8") as _f:
        pnf_data = json.load(_f)
    for _entry in pnf_data:
        _drug = _entry.get("drug","").lower().strip().strip("﻿​\r")
        _text = _entry.get("text","")
        if not _drug: continue
        _clean = _clean_text(_text)
        _entry["clean_text"] = _clean
        drug_index[_drug] = _entry
        _norm = re.sub(r"[^a-z0-9 ]","",_drug).strip()
        if _norm and _norm != _drug: drug_index[_norm] = _entry
        drug_names.append(_drug)
        for _i in range(1, min(len(_drug),10)+1):
            prefix_index.setdefault(_drug[:_i],[]).append(_entry)
        for _w in set(re.findall(r"\b\w+\b",_clean.lower())):
            if len(_w) > 3: content_index.setdefault(_w,[]).append(_entry)

# --- Models ---
class AskRequest(BaseModel):
    question: str

class SourceItem(BaseModel):
    num: int; title: str; section: str; snippet: str; lastUpdated: str

class AskResponse(BaseModel):
    body: str; sources: List[SourceItem]

# --- Firebase Auth Helper ---

def _build_ai_notice() -> str:
    return (
        '<p class="ai-notice" style="'
        "background:#e8f0fe;border-left:4px solid #4285f4;"
        "padding:0.6em 0.8em;border-radius:4px;margin-bottom:0.8em;"
        'font-size:0.9em;">'
        "<strong>&#10024; AI-Synthesized Summary:</strong> Generated by PNF Assistant AI. "
        "Always cross-check with PNF and authoritative sources."
        "</p>"
    )

def synthesize_interaction(drugs: list, is_question: bool = False, full_query: str = "") -> str:
    if _GEMMA_MODEL is None:
        raise RuntimeError("Gemini not configured.")
    
    pnf_list = ", ".join(drug_names)
    
    if is_question:
        prompt = (f"Answer the following clinical question based strictly on standard medical guidelines and the Philippine National Formulary context.\n\n"
                  f"AVAILABLE PNF DRUGS:\n{pnf_list}\n\n"
                  f"IMPORTANT: If you recommend or suggest any medications, they MUST be chosen EXCLUSIVELY from the 'AVAILABLE PNF DRUGS' list above.\n\n"
                  f"Question: {full_query}\n\n"
                  "Provide a concise, professional clinical response in plain text. "
                  "Do not include disclaimers — they are added by the UI.")
    else:
        prompt = ("Provide a concise clinical drug interaction summary for the following "
                  "medications: " + ", ".join(drugs) + ". Cover mechanism, severity, and clinical management in plain text.\n"
                  "If you suggest alternative treatments, they MUST be chosen from this list: " + pnf_list + "\n"
                  "Do not include disclaimers — they are added by the UI.")
    return _GEMMA_MODEL.generate_content(prompt).text

def _verify_firebase_token(authorization: Optional[str]) -> Optional[dict]:
    """Verify Firebase ID token from Authorization header. Returns {uid, email} or None."""
    if not _FB_AUTH or not authorization or not authorization.startswith("Bearer "):
        return None
    try:
        token = authorization[7:].strip()
        decoded = _FB_AUTH.verify_id_token(token)
        return {"uid": decoded["uid"], "email": decoded.get("email","")}
    except Exception:
        return None

# --- Search ---
@lru_cache(maxsize=500)
def _search_index(query: str):
    q = query.lower().strip()
    if not q: return None
    words = re.findall(r"\b\w+\b", q)

    if q in drug_index: return drug_index[q]
    q_norm = re.sub(r"[^a-z0-9 ]","",q).strip()
    if q_norm != q and q_norm in drug_index: return drug_index[q_norm]
    if q in prefix_index: return prefix_index[q][0]
    if len(words) == 1 and words[0] not in drug_index:
        if q_norm not in drug_index: return None
    if drug_names and len(words) <= 3:
        best, score, _ = process.extractOne(q, drug_names, scorer=fuzz.WRatio)
        if score >= 90: return drug_index[best]

    _stop = {"what","are","the","for","in","of","a","an","and","to","is","how",
             "does","do","can","with","this","that","from","by","on","at","or"}
    _generic = {"first","line","second","third","use","used","drug","dose",
                "treatment","treatments","adults","adult","children","patient","patients"}
    mw = [w for w in words if w not in _stop and len(w) >= 3]
    specific = [w for w in mw if w not in _generic]

    if len(mw) >= 2 and specific:
        hits = []
        for e in pnf_data:
            tn = re.sub(r"[^a-z0-9 ]"," ",e.get("clean_text","").lower())
            if not any(w in tn for w in specific): continue
            for i in range(len(mw)-1):
                if mw[i]+" "+mw[i+1] in tn: hits.append(e); break
        if hits:
            hits.sort(key=lambda e: sum(1 for w in specific if w in
                re.sub(r"[^a-z0-9 ]"," ",e.get("clean_text","").lower())), reverse=True)
            return hits[0]

    cands = []
    for w in mw:
        if len(w) >= 4 and w in content_index: cands.extend(content_index[w])
    if cands:
        def _sc(e):
            s, d, t = 0, e["drug"].lower(), e.get("clean_text","").lower()
            if q == d: s += 100
            elif q in d: s += 60
            h = sum(1 for w in mw if w in t)
            return s + (h*10 if h >= 2 else 0)
        unique = list({c["drug"]: c for c in cands}.values())
        return sorted(unique, key=_sc, reverse=True)[0]
    return None

# --- Helpers ---
def _format_text_as_html(text: str) -> str:
    parts = []
    for line in text.splitlines():
        s = line.strip()
        if not s: continue
        core = s.rstrip(":.")
        if len(core) >= 3 and core == core.upper() and core.replace(" ","").isalpha():
            parts.append(f"<p><strong>{s}</strong></p>")
        else: parts.append(f"<p>{s}</p>")
    return "\n".join(parts)

def _build_ams_alert(dn: str) -> str:
    if dn.lower().strip() in AMS_RESTRICTED:
        return ('<p class="ams-alert" style="background:#fff3cd;border-left:4px solid #ffc107;'
                'padding:0.6em 0.8em;border-radius:4px;margin-bottom:0.8em;">'
                f"<strong>&#9888; AMS Restricted</strong> &mdash; <em>{dn}</em> requires AMS approval.</p>")
    return ""

def _build_citation(n: int, dn: str) -> str:
    return f'<a class="citation" href="#source-{n}" title="PNF &mdash; {dn}">[{n}]</a>'

def _resolver_notice(brand: str, generic: str, source: str = "mims") -> str:
    label = "MIMS brand database" if source == "mims" else "Gemini AI"
    return (f'<p class="resolver-notice" style="background:#e6ffed;border-left:4px solid #4ade80;'
            f'padding:0.6em 0.8em;border-radius:4px;margin-bottom:0.8em;font-size:0.9em;">'
            f'<strong>Brand &rarr; Generic:</strong> "{brand}" &rarr; <em>{generic.upper()}</em> via {label}.</p>')

def _resolve_one(term: str):
    t = term.lower().strip()
    if t in drug_index: return drug_index[t], "none", None
    tn = re.sub(r"[^a-z0-9 ]","",t).strip()
    if tn != t and tn in drug_index: return drug_index[tn], "none", None
    from ai_resolver import MIMS_BRAND_TO_GENERIC
    mk = term.strip().upper()
    mh = MIMS_BRAND_TO_GENERIC.get(mk) or (MIMS_BRAND_TO_GENERIC.get(mk.split()[0]) if " " in mk else None)
    if mh and mh.lower().strip() in drug_index:
        return drug_index[mh.lower().strip()], "mims", mh.lower().strip()
    m = _search_index(term)
    return (m, "none", None) if m else (None, None, None)

# --- Firestore Chat Save (async, non-blocking) ---
def _save_chat(uid: str, question: str, drugs: list):
    if not _FIRESTORE or not uid: return
    try:
        _FIRESTORE.collection("users").document(uid).collection("chats").add({
            "question": question,
            "drugs": drugs,
            "timestamp": firestore.SERVER_TIMESTAMP,
        })
    except Exception as e:
        print(f"[Firestore] Save error: {e}")

# ======================== ROUTES ========================

@app.get("/", response_class=HTMLResponse, include_in_schema=False)
async def serve_frontend():
    p = os.path.join(BASE_DIR, "index.html")
    if not os.path.exists(p): raise HTTPException(404, "index.html not found")
    with open(p, "r", encoding="utf-8") as f: return HTMLResponse(content=f.read())

@app.get("/health")
async def health():
    from ai_resolver import get_mims_status
    return {**{"status":"ok","version":"4.0.0","entries_loaded":len(pnf_data),
        "gemma_available":_GEMMA_MODEL is not None,
        "firebase_available":_FB_AUTH is not None,
        "firestore_available":_FIRESTORE is not None}, **get_mims_status()}

@app.get("/api/auth/me")
async def me(authorization: Optional[str] = Header(None)):
    user = _verify_firebase_token(authorization)
    if not user: raise HTTPException(401, "Not authenticated")
    return user

@app.get("/api/chats")
async def get_chats(authorization: Optional[str] = Header(None)):
    user = _verify_firebase_token(authorization)
    if not user: raise HTTPException(401, "Not authenticated")
    if not _FIRESTORE: return {"chats": []}
    try:
        docs = (_FIRESTORE.collection("users").document(user["uid"])
                .collection("chats").order_by("timestamp", direction=firestore.Query.DESCENDING)
                .limit(50).stream())
        chats = []
        for doc in docs:
            d = doc.to_dict()
            chats.append({"id": doc.id, "question": d.get("question",""),
                          "drugs": d.get("drugs",[]), "timestamp": str(d.get("timestamp",""))})
        return {"chats": chats}
    except Exception as e:
        return {"chats": [], "error": str(e)}

@app.post("/api/pnf/ask", response_model=AskResponse)
async def ask(req: AskRequest, authorization: Optional[str] = Header(None)):
    question = req.question.strip()
    if not question: raise HTTPException(422, "Empty query")
    q = question.lower().strip()
    q_words = re.findall(r"\b\w+\b", q)

    # Extract entities
    _splitters = [" and ", " with ", " vs ", " versus ", ", "]
    entities = [q]
    for sp in _splitters:
        if sp in q:
            entities = [p.strip() for p in q.split(sp.strip()) if p.strip()]
            break

    _qw = {"what","how","which","when","where","why","can","does","should","list","tell","give","compare"}
    is_question = len(q_words) > 4 or (q_words and q_words[0] in _qw)
    is_interaction = len(entities) > 1

    if is_question or is_interaction:
        try:
            ai_text = synthesize_interaction(drugs=entities, is_question=is_question, full_query=question)
            ai_html = _format_text_as_html(ai_text)
            body_html = "\n".join([_build_ai_notice(), ai_html])
            
            title_text = "AI-Synthesized Answer" if is_question else "AI-Synthesized Summary"
            section_text = "Clinical Question" if is_question else f"Drug Interaction: {' + '.join(entities)}"

            user = _verify_firebase_token(authorization)
            if user:
                _save_chat(user["uid"], question, entities)

            return AskResponse(
                body=body_html,
                sources=[SourceItem(
                    num=1,
                    title=title_text,
                    section=section_text,
                    snippet="Generated by PNF Assistant AI. Always cross-check with PNF and authoritative sources.",
                    lastUpdated="Live",
                )],
            )
        except Exception as e:
            err_html = (
                f"<p>Unable to synthesize response: {str(e)[:120]}</p>"
                "<p>Try searching specific drug names in the PNF library instead.</p>"
            )
            return AskResponse(body=err_html, sources=[])


    results = []
    for ent in entities:
        ew = re.findall(r"\b\w+\b", ent)
        is_brand = len(ew) <= 3 and not is_question
        m, rv, gen = _resolve_one(ent)
        if m is None and is_brand:
            g = ai_resolve_generic(ent, _GEMMA_MODEL)
            if g and g.lower().strip() in drug_index:
                m, rv, gen = drug_index[g.lower().strip()], "gemini", g.lower().strip()
        if m: results.append((ent, m, rv, gen))

    if not results:
        m = _search_index(question)
        if m: results.append((question, m, "none", None))

    if not results:
        return AskResponse(body=f"<p>No results for <strong>{question}</strong>. Try a generic drug name.</p>", sources=[])

    # Build response
    body_parts, sources, drug_list = [], [], []
    for i, (ent, match, resolver, gen) in enumerate(results):
        dn = match.get("drug", ent); ct = match.get("clean_text","")
        notice = _resolver_notice(ent, gen, source=resolver) if resolver in ("mims","gemini") and gen else ""
        cite = _build_citation(i+1, dn)
        body_parts.append(notice + _build_ams_alert(dn) + _format_text_as_html(ct) + f"\n<p>{cite}</p>")
        snip = ct[:200].strip()
        if len(ct) > 200:
            sp = snip.rfind(" "); snip = (snip[:sp] if sp > 0 else snip) + "..."
        sources.append(SourceItem(num=i+1, title="Philippine National Formulary",
            section=f"Drug Monograph &mdash; {dn}", snippet=snip, lastUpdated="Apr 2026"))
        drug_list.append(dn)

    # Save to Firestore (if authenticated)
    user = _verify_firebase_token(authorization)
    if user:
        _save_chat(user["uid"], question, drug_list)

    sep = '<hr style="margin:1.5em 0;border:none;border-top:1px solid #ddd;">'
    return AskResponse(body=sep.join(body_parts), sources=sources)

if __name__ == "__main__":
    import uvicorn; uvicorn.run("api:app", host="0.0.0.0", port=8501, reload=True)
